# Statistical Inference - Course project part 1
## Simulation of Exponential Distribution
### by Thorbjørn Larsen

##Overview
This report will investigate of the exponential distribution in R with a comparison to the Central Limit Theorem.

> In a few (2-3) sentences explain what is going to be reported on.

##Simulations

> Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.

##Sample Mean versus Theoretical Mean
> Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.

##Sample Variance versus Theoretical Variance
> Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.

##Distribution
> Via figures and text, explain how one can tell the distribution is approximately normal.